<?php

namespace App;

use App\Scopes\BuyerScope;

class Buyer extends User
{
    protected $table = 'users';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new BuyerScope);
    }

    public function transactions() {
        return $this->hasMany(Transaction::class);
    }
}
